"""
Bake-off extension: does PLAYMAKING/CREATION add to box + synergy offense?

Box assists undercount creation — they require the teammate to make the shot. The
tracking data has creation independent of finishing: POTENTIAL_AST (passes that
would be assists) and AST_POINTS_CREATED (points generated by a player's passes).
Test whether adding these improves team-offense prediction beyond box OBPM +
synergy value, out-of-sample (LOSO CV). If yes, fold into WAR.

Usage: python scripts/112_creation_value.py
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SYN = ROOT / "data" / "parquet" / "player_synergy.parquet"
TRK = ROOT / "data" / "parquet" / "player_tracking.parquet"
WAR = ROOT / "data" / "parquet" / "player_seasons_war.parquet"
PS = ROOT / "data" / "parquet" / "player_seasons.parquet"
TG = ROOT / "data" / "parquet" / "team_games.parquet"
ORDER = [f"{y}-{str(y + 1)[2:]}" for y in range(2013, 2026)]
PREV = {s: ORDER[i - 1] for i, s in enumerate(ORDER) if i}


def loso(d, y, cols, seasons):
    pred = np.full(len(d), np.nan)
    for s in np.unique(seasons):
        tr, te = seasons != s, seasons == s
        A = np.column_stack([np.ones(tr.sum())] + [d[c].to_numpy()[tr] for c in cols])
        b, *_ = np.linalg.lstsq(A, y[tr], rcond=None)
        pred[te] = np.column_stack([np.ones(te.sum())] + [d[c].to_numpy()[te] for c in cols]) @ b
    return np.sqrt(np.mean((y - pred) ** 2)), np.corrcoef(pred, y)[0, 1]


def main() -> None:
    syn = pd.read_parquet(SYN); off = syn[syn.side == "offensive"].copy()
    lg = (off.groupby(["SEASON", "play_type"])
             .apply(lambda g: np.average(g.ppp.fillna(0), weights=g.poss.fillna(0) + 1e-9),
                    include_groups=False).rename("lg").reset_index())
    off = off.merge(lg, on=["SEASON", "play_type"])
    off["v"] = off.poss.fillna(0) * (off.ppp.fillna(0) - off.lg)
    syn_val = off.groupby(["PLAYER_ID", "SEASON"]).v.sum().rename("syn").reset_index()

    trk = pd.read_parquet(TRK); trk = trk[trk.MIN > 0]
    crea = trk[["PLAYER_ID", "SEASON", "POTENTIAL_AST", "AST_POINTS_CREATED"]].copy()

    war = pd.read_parquet(WAR, columns=["PLAYER_ID", "SEASON", "OBPM"])
    ps = pd.read_parquet(PS, columns=["PLAYER_ID", "SEASON", "TEAM", "MIN"])
    m = (ps.merge(war, on=["PLAYER_ID", "SEASON"], how="left")
           .merge(syn_val, on=["PLAYER_ID", "SEASON"], how="left")
           .merge(crea, on=["PLAYER_ID", "SEASON"], how="left"))
    m = m[m.MIN >= 500].copy()
    for c in ["syn", "POTENTIAL_AST", "AST_POINTS_CREATED"]:
        m[c] = m[c].fillna(0.0)

    tg = pd.read_parquet(TG); tg = tg[tg.SEASON_TYPE == "Regular Season"]
    ortg = {(t, s): g.offensiveRating.mean() for (t, s), g in tg.groupby(["TEAM_TRICODE", "SEASON"])}
    look = {c: {(r.PLAYER_ID, r.SEASON): getattr(r, c) for r in m.itertuples()}
            for c in ["OBPM", "syn", "POTENTIAL_AST", "AST_POINTS_CREATED"]}

    rows = []
    for (tri, s), g in m.groupby(["TEAM", "SEASON"]):
        p = PREV.get(s)
        if p is None or (tri, s) not in ortg:
            continue
        recs = [(r.MIN, {c: look[c].get((r.PLAYER_ID, p)) for c in look}) for r in g.itertuples()]
        recs = [(w, v) for w, v in recs if v["OBPM"] is not None and not np.isnan(v["OBPM"])]
        if len(recs) < 5:
            continue
        W = sum(w for w, _ in recs)
        row = {"season": s, "ortg": ortg[(tri, s)]}
        for c in look:
            row[c] = sum(w * (v[c] or 0) for w, v in recs) / W
        rows.append(row)
    d = pd.DataFrame(rows)
    for c in ["ortg", "OBPM", "syn", "POTENTIAL_AST", "AST_POINTS_CREATED"]:
        d[c + "_dm"] = d[c] - d.groupby("season")[c].transform("mean")
    y = d.ortg_dm.to_numpy(); seasons = d.season.to_numpy()

    print(f"Creation bake-off — {len(d)} team-seasons (predict team ORtg, LOSO CV)\n")
    for name, cols in [("box OBPM", ["OBPM_dm"]),
                       ("box + synergy", ["OBPM_dm", "syn_dm"]),
                       ("box + synergy + potential_ast", ["OBPM_dm", "syn_dm", "POTENTIAL_AST_dm"]),
                       ("box + synergy + ast_pts_created", ["OBPM_dm", "syn_dm", "AST_POINTS_CREATED_dm"]),
                       ("box + synergy + both creation", ["OBPM_dm", "syn_dm", "POTENTIAL_AST_dm", "AST_POINTS_CREATED_dm"])]:
        rmse, r = loso(d, y, cols, seasons)
        print(f"  {name:<34} CV RMSE {rmse:.3f}  corr {r:+.3f}")


if __name__ == "__main__":
    main()
