window.NBAI_DATA = {
  "generated": "2026-07-18",
  "season": "2025-26",
  "model": {
    "games": "16,758",
    "seasons": 13,
    "accuracy": "65.2%",
    "logloss": "0.626"
  },
  "teams": [
    {
      "name": "New York Knicks",
      "abbr": "NYK",
      "elo": 1799,
      "w": 53,
      "l": 29,
      "c": "#F58426"
    },
    {
      "name": "San Antonio Spurs",
      "abbr": "SAS",
      "elo": 1776,
      "w": 62,
      "l": 20,
      "c": "#9EA8B0"
    },
    {
      "name": "Oklahoma City Thunder",
      "abbr": "OKC",
      "elo": 1761,
      "w": 64,
      "l": 18,
      "c": "#007AC1"
    },
    {
      "name": "Detroit Pistons",
      "abbr": "DET",
      "elo": 1689,
      "w": 60,
      "l": 22,
      "c": "#C8102E"
    },
    {
      "name": "Boston Celtics",
      "abbr": "BOS",
      "elo": 1656,
      "w": 56,
      "l": 26,
      "c": "#007A33"
    },
    {
      "name": "Charlotte Hornets",
      "abbr": "CHA",
      "elo": 1631,
      "w": 44,
      "l": 38,
      "c": "#00788C"
    },
    {
      "name": "Denver Nuggets",
      "abbr": "DEN",
      "elo": 1631,
      "w": 54,
      "l": 28,
      "c": "#0E2240"
    },
    {
      "name": "Cleveland Cavaliers",
      "abbr": "CLE",
      "elo": 1624,
      "w": 52,
      "l": 30,
      "c": "#860038"
    },
    {
      "name": "Houston Rockets",
      "abbr": "HOU",
      "elo": 1612,
      "w": 52,
      "l": 30,
      "c": "#CE1141"
    },
    {
      "name": "Los Angeles Lakers",
      "abbr": "LAL",
      "elo": 1592,
      "w": 53,
      "l": 29,
      "c": "#552583"
    },
    {
      "name": "Minnesota Timberwolves",
      "abbr": "MIN",
      "elo": 1586,
      "w": 49,
      "l": 33,
      "c": "#236192"
    },
    {
      "name": "Atlanta Hawks",
      "abbr": "ATL",
      "elo": 1567,
      "w": 46,
      "l": 36,
      "c": "#E03A3E"
    },
    {
      "name": "Toronto Raptors",
      "abbr": "TOR",
      "elo": 1561,
      "w": 46,
      "l": 36,
      "c": "#CE1141"
    },
    {
      "name": "Orlando Magic",
      "abbr": "ORL",
      "elo": 1559,
      "w": 45,
      "l": 37,
      "c": "#0077C0"
    },
    {
      "name": "Philadelphia 76ers",
      "abbr": "PHI",
      "elo": 1551,
      "w": 45,
      "l": 37,
      "c": "#006BB6"
    },
    {
      "name": "Phoenix Suns",
      "abbr": "PHX",
      "elo": 1542,
      "w": 45,
      "l": 37,
      "c": "#E56020"
    },
    {
      "name": "LA Clippers",
      "abbr": "LAC",
      "elo": 1534,
      "w": 42,
      "l": 40,
      "c": "#C8102E"
    },
    {
      "name": "Portland Trail Blazers",
      "abbr": "POR",
      "elo": 1516,
      "w": 42,
      "l": 40,
      "c": "#E03A3E"
    },
    {
      "name": "Miami Heat",
      "abbr": "MIA",
      "elo": 1507,
      "w": 43,
      "l": 39,
      "c": "#98002E"
    },
    {
      "name": "Golden State Warriors",
      "abbr": "GSW",
      "elo": 1423,
      "w": 37,
      "l": 45,
      "c": "#1D428A"
    },
    {
      "name": "New Orleans Pelicans",
      "abbr": "NOP",
      "elo": 1397,
      "w": 26,
      "l": 56,
      "c": "#85714D"
    },
    {
      "name": "Chicago Bulls",
      "abbr": "CHI",
      "elo": 1348,
      "w": 31,
      "l": 51,
      "c": "#CE1141"
    },
    {
      "name": "Milwaukee Bucks",
      "abbr": "MIL",
      "elo": 1344,
      "w": 32,
      "l": 50,
      "c": "#00471B"
    },
    {
      "name": "Dallas Mavericks",
      "abbr": "DAL",
      "elo": 1335,
      "w": 26,
      "l": 56,
      "c": "#00538C"
    },
    {
      "name": "Indiana Pacers",
      "abbr": "IND",
      "elo": 1334,
      "w": 19,
      "l": 63,
      "c": "#FDBB30"
    },
    {
      "name": "Sacramento Kings",
      "abbr": "SAC",
      "elo": 1325,
      "w": 22,
      "l": 60,
      "c": "#5A2D81"
    },
    {
      "name": "Memphis Grizzlies",
      "abbr": "MEM",
      "elo": 1277,
      "w": 25,
      "l": 57,
      "c": "#5D76A9"
    },
    {
      "name": "Utah Jazz",
      "abbr": "UTA",
      "elo": 1275,
      "w": 22,
      "l": 60,
      "c": "#00471B"
    },
    {
      "name": "Brooklyn Nets",
      "abbr": "BKN",
      "elo": 1250,
      "w": 20,
      "l": 62,
      "c": "#777777"
    },
    {
      "name": "Washington Wizards",
      "abbr": "WAS",
      "elo": 1199,
      "w": 17,
      "l": 65,
      "c": "#002B5C"
    }
  ],
  "players": [
    {
      "rank": 1,
      "player": "Nikola Joki\u0107",
      "team": "DEN",
      "war": 10.4,
      "poe": 22.3,
      "def": -0.1,
      "mpg": 34.8,
      "pts": 27.7,
      "reb": 12.9,
      "ast": 10.7,
      "c": "#0E2240"
    },
    {
      "rank": 2,
      "player": "Victor Wembanyama",
      "team": "SAS",
      "war": 9.9,
      "poe": -2.3,
      "def": 3.9,
      "mpg": 29.2,
      "pts": 25.0,
      "reb": 11.5,
      "ast": 3.1,
      "c": "#9EA8B0"
    },
    {
      "rank": 3,
      "player": "Luka Don\u010di\u0107",
      "team": "LAL",
      "war": 9.5,
      "poe": 14.4,
      "def": -0.6,
      "mpg": 35.8,
      "pts": 33.5,
      "reb": 7.7,
      "ast": 8.3,
      "c": "#552583"
    },
    {
      "rank": 4,
      "player": "Karl-Anthony Towns",
      "team": "NYK",
      "war": 9.3,
      "poe": 2.2,
      "def": -2.1,
      "mpg": 31.0,
      "pts": 20.1,
      "reb": 11.9,
      "ast": 3.0,
      "c": "#F58426"
    },
    {
      "rank": 5,
      "player": "Jaylen Brown",
      "team": "BOS",
      "war": 8.1,
      "poe": 6.3,
      "def": -1.3,
      "mpg": 34.4,
      "pts": 28.7,
      "reb": 6.9,
      "ast": 5.1,
      "c": "#007A33"
    },
    {
      "rank": 6,
      "player": "Jalen Johnson",
      "team": "ATL",
      "war": 7.8,
      "poe": 1.0,
      "def": -0.4,
      "mpg": 35.2,
      "pts": 22.5,
      "reb": 10.3,
      "ast": 7.9,
      "c": "#E03A3E"
    },
    {
      "rank": 7,
      "player": "Kawhi Leonard",
      "team": "LAC",
      "war": 7.5,
      "poe": 13.2,
      "def": 1.2,
      "mpg": 32.1,
      "pts": 27.9,
      "reb": 6.4,
      "ast": 3.6,
      "c": "#C8102E"
    },
    {
      "rank": 8,
      "player": "Jalen Duren",
      "team": "DET",
      "war": 7.0,
      "poe": 9.9,
      "def": -0.8,
      "mpg": 28.2,
      "pts": 19.5,
      "reb": 10.5,
      "ast": 2.0,
      "c": "#C8102E"
    },
    {
      "rank": 9,
      "player": "Bam Adebayo",
      "team": "MIA",
      "war": 6.8,
      "poe": -7.3,
      "def": 0.7,
      "mpg": 32.4,
      "pts": 20.1,
      "reb": 10.0,
      "ast": 3.2,
      "c": "#98002E"
    },
    {
      "rank": 10,
      "player": "Shai Gilgeous-Alexander",
      "team": "OKC",
      "war": 6.7,
      "poe": 14.4,
      "def": 1.1,
      "mpg": 33.2,
      "pts": 31.1,
      "reb": 4.3,
      "ast": 6.6,
      "c": "#007AC1"
    },
    {
      "rank": 11,
      "player": "Paolo Banchero",
      "team": "ORL",
      "war": 6.2,
      "poe": -5.5,
      "def": -0.9,
      "mpg": 34.7,
      "pts": 22.2,
      "reb": 8.4,
      "ast": 5.2,
      "c": "#0077C0"
    },
    {
      "rank": 12,
      "player": "Alperen Sengun",
      "team": "HOU",
      "war": 6.1,
      "poe": 2.6,
      "def": -1.1,
      "mpg": 33.3,
      "pts": 20.4,
      "reb": 8.9,
      "ast": 6.2,
      "c": "#CE1141"
    },
    {
      "rank": 13,
      "player": "Chet Holmgren",
      "team": "OKC",
      "war": 5.5,
      "poe": 7.2,
      "def": 3.2,
      "mpg": 28.9,
      "pts": 17.1,
      "reb": 8.9,
      "ast": 1.7,
      "c": "#007AC1"
    },
    {
      "rank": 14,
      "player": "Kevin Durant",
      "team": "HOU",
      "war": 5.5,
      "poe": 19.1,
      "def": 0.1,
      "mpg": 36.4,
      "pts": 26.0,
      "reb": 5.5,
      "ast": 4.8,
      "c": "#CE1141"
    },
    {
      "rank": 15,
      "player": "Donovan Mitchell",
      "team": "CLE",
      "war": 5.3,
      "poe": 6.8,
      "def": -0.6,
      "mpg": 33.5,
      "pts": 27.9,
      "reb": 4.5,
      "ast": 5.7,
      "c": "#860038"
    },
    {
      "rank": 16,
      "player": "Deni Avdija",
      "team": "POR",
      "war": 5.3,
      "poe": -1.2,
      "def": -1.6,
      "mpg": 33.3,
      "pts": 24.2,
      "reb": 6.9,
      "ast": 6.7,
      "c": "#E03A3E"
    },
    {
      "rank": 17,
      "player": "Scottie Barnes",
      "team": "TOR",
      "war": 5.0,
      "poe": -1.0,
      "def": 0.9,
      "mpg": 33.5,
      "pts": 18.1,
      "reb": 7.5,
      "ast": 5.9,
      "c": "#CE1141"
    },
    {
      "rank": 18,
      "player": "Julius Randle",
      "team": "MIN",
      "war": 5.0,
      "poe": -3.5,
      "def": -2.0,
      "mpg": 33.0,
      "pts": 21.1,
      "reb": 6.7,
      "ast": 5.0,
      "c": "#236192"
    },
    {
      "rank": 19,
      "player": "Tyrese Maxey",
      "team": "PHI",
      "war": 4.9,
      "poe": 3.8,
      "def": 0.8,
      "mpg": 38.0,
      "pts": 28.3,
      "reb": 4.1,
      "ast": 6.6,
      "c": "#006BB6"
    },
    {
      "rank": 20,
      "player": "Donovan Clingan",
      "team": "POR",
      "war": 4.9,
      "poe": -6.5,
      "def": 1.9,
      "mpg": 27.2,
      "pts": 12.1,
      "reb": 11.6,
      "ast": 2.1,
      "c": "#E03A3E"
    },
    {
      "rank": 21,
      "player": "Anthony Edwards",
      "team": "MIN",
      "war": 4.9,
      "poe": 7.3,
      "def": 0.5,
      "mpg": 35.0,
      "pts": 28.8,
      "reb": 5.0,
      "ast": 3.7,
      "c": "#236192"
    },
    {
      "rank": 22,
      "player": "Cade Cunningham",
      "team": "DET",
      "war": 4.8,
      "poe": 1.7,
      "def": -0.3,
      "mpg": 33.9,
      "pts": 23.9,
      "reb": 5.5,
      "ast": 9.9,
      "c": "#C8102E"
    },
    {
      "rank": 23,
      "player": "Michael Porter Jr.",
      "team": "BKN",
      "war": 4.5,
      "poe": 4.7,
      "def": -1.5,
      "mpg": 32.5,
      "pts": 24.2,
      "reb": 7.1,
      "ast": 3.0,
      "c": "#777777"
    },
    {
      "rank": 24,
      "player": "Pascal Siakam",
      "team": "IND",
      "war": 4.5,
      "poe": 7.2,
      "def": -1.0,
      "mpg": 33.2,
      "pts": 24.0,
      "reb": 6.6,
      "ast": 3.8,
      "c": "#FDBB30"
    },
    {
      "rank": 25,
      "player": "Evan Mobley",
      "team": "CLE",
      "war": 4.4,
      "poe": -4.5,
      "def": 1.3,
      "mpg": 31.9,
      "pts": 18.2,
      "reb": 9.0,
      "ast": 3.6,
      "c": "#860038"
    },
    {
      "rank": 26,
      "player": "LaMelo Ball",
      "team": "CHA",
      "war": 4.4,
      "poe": 1.7,
      "def": -1.9,
      "mpg": 28.0,
      "pts": 20.1,
      "reb": 4.8,
      "ast": 7.1,
      "c": "#00788C"
    },
    {
      "rank": 27,
      "player": "Giannis Antetokounmpo",
      "team": "MIL",
      "war": 4.4,
      "poe": 3.2,
      "def": 0.5,
      "mpg": 28.9,
      "pts": 27.6,
      "reb": 9.8,
      "ast": 5.4,
      "c": "#00471B"
    },
    {
      "rank": 28,
      "player": "Cooper Flagg",
      "team": "DAL",
      "war": 4.4,
      "poe": -3.2,
      "def": 0.7,
      "mpg": 33.5,
      "pts": 21.0,
      "reb": 6.7,
      "ast": 4.5,
      "c": "#00538C"
    },
    {
      "rank": 29,
      "player": "Kel'el Ware",
      "team": "MIA",
      "war": 4.3,
      "poe": -3.2,
      "def": 0.7,
      "mpg": 22.1,
      "pts": 11.1,
      "reb": 9.0,
      "ast": 0.7,
      "c": "#98002E"
    },
    {
      "rank": 30,
      "player": "Derik Queen",
      "team": "NOP",
      "war": 4.2,
      "poe": -8.9,
      "def": -0.1,
      "mpg": 25.0,
      "pts": 11.7,
      "reb": 7.1,
      "ast": 3.7,
      "c": "#85714D"
    },
    {
      "rank": 31,
      "player": "James Harden",
      "team": "LAC",
      "war": 4.1,
      "poe": 2.3,
      "def": -1.0,
      "mpg": 34.8,
      "pts": 23.6,
      "reb": 4.8,
      "ast": 8.0,
      "c": "#C8102E"
    },
    {
      "rank": 32,
      "player": "Brandon Ingram",
      "team": "TOR",
      "war": 4.1,
      "poe": 3.5,
      "def": -0.3,
      "mpg": 33.8,
      "pts": 21.5,
      "reb": 5.6,
      "ast": 3.7,
      "c": "#CE1141"
    },
    {
      "rank": 33,
      "player": "Rudy Gobert",
      "team": "MIN",
      "war": 4.0,
      "poe": -6.2,
      "def": 1.6,
      "mpg": 31.3,
      "pts": 10.9,
      "reb": 11.5,
      "ast": 1.7,
      "c": "#236192"
    },
    {
      "rank": 34,
      "player": "Kyle Filipowski",
      "team": "UTA",
      "war": 4.0,
      "poe": 2.0,
      "def": -3.4,
      "mpg": 23.4,
      "pts": 11.4,
      "reb": 7.2,
      "ast": 2.6,
      "c": "#00471B"
    },
    {
      "rank": 35,
      "player": "Jamal Murray",
      "team": "DEN",
      "war": 4.0,
      "poe": 12.3,
      "def": -0.8,
      "mpg": 35.4,
      "pts": 25.4,
      "reb": 4.4,
      "ast": 7.1,
      "c": "#0E2240"
    },
    {
      "rank": 36,
      "player": "Neemias Queta",
      "team": "BOS",
      "war": 3.9,
      "poe": 11.5,
      "def": 0.0,
      "mpg": 25.3,
      "pts": 10.2,
      "reb": 8.4,
      "ast": 1.7,
      "c": "#007A33"
    },
    {
      "rank": 37,
      "player": "LeBron James",
      "team": "LAL",
      "war": 3.8,
      "poe": 3.7,
      "def": 1.2,
      "mpg": 33.2,
      "pts": 20.9,
      "reb": 6.1,
      "ast": 7.2,
      "c": "#552583"
    },
    {
      "rank": 38,
      "player": "Nikola Vu\u010devi\u0107",
      "team": "CHI",
      "war": 3.6,
      "poe": 8.6,
      "def": -0.8,
      "mpg": 28.4,
      "pts": 15.1,
      "reb": 8.4,
      "ast": 3.3,
      "c": "#CE1141"
    },
    {
      "rank": 39,
      "player": "Devin Booker",
      "team": "PHX",
      "war": 3.6,
      "poe": 1.7,
      "def": -1.5,
      "mpg": 33.5,
      "pts": 26.1,
      "reb": 3.9,
      "ast": 6.0,
      "c": "#E56020"
    },
    {
      "rank": 40,
      "player": "Naz Reid",
      "team": "MIN",
      "war": 3.5,
      "poe": 5.3,
      "def": 0.0,
      "mpg": 26.1,
      "pts": 13.6,
      "reb": 6.2,
      "ast": 2.2,
      "c": "#236192"
    },
    {
      "rank": 41,
      "player": "Jarrett Allen",
      "team": "CLE",
      "war": 3.5,
      "poe": 8.7,
      "def": 2.8,
      "mpg": 27.1,
      "pts": 15.4,
      "reb": 8.5,
      "ast": 1.8,
      "c": "#860038"
    },
    {
      "rank": 42,
      "player": "Jalen Brunson",
      "team": "NYK",
      "war": 3.5,
      "poe": 5.9,
      "def": -2.2,
      "mpg": 35.0,
      "pts": 26.0,
      "reb": 3.3,
      "ast": 6.8,
      "c": "#F58426"
    },
    {
      "rank": 43,
      "player": "Joel Embiid",
      "team": "PHI",
      "war": 3.5,
      "poe": 6.8,
      "def": 0.1,
      "mpg": 31.6,
      "pts": 26.9,
      "reb": 7.7,
      "ast": 3.9,
      "c": "#006BB6"
    },
    {
      "rank": 44,
      "player": "Onyeka Okongwu",
      "team": "ATL",
      "war": 3.4,
      "poe": 4.7,
      "def": -1.0,
      "mpg": 31.0,
      "pts": 15.2,
      "reb": 7.6,
      "ast": 3.1,
      "c": "#E03A3E"
    },
    {
      "rank": 45,
      "player": "Brandon Miller",
      "team": "CHA",
      "war": 3.4,
      "poe": 2.4,
      "def": -1.0,
      "mpg": 30.3,
      "pts": 20.2,
      "reb": 4.9,
      "ast": 3.3,
      "c": "#00788C"
    },
    {
      "rank": 46,
      "player": "Zion Williamson",
      "team": "NOP",
      "war": 3.3,
      "poe": 9.6,
      "def": -0.8,
      "mpg": 29.7,
      "pts": 21.0,
      "reb": 5.7,
      "ast": 3.2,
      "c": "#85714D"
    },
    {
      "rank": 47,
      "player": "Bobby Portis",
      "team": "MIL",
      "war": 3.3,
      "poe": 16.5,
      "def": -1.7,
      "mpg": 24.2,
      "pts": 13.7,
      "reb": 6.4,
      "ast": 1.6,
      "c": "#00471B"
    },
    {
      "rank": 48,
      "player": "Maxime Raynaud",
      "team": "SAC",
      "war": 3.2,
      "poe": 17.3,
      "def": -2.0,
      "mpg": 26.5,
      "pts": 12.5,
      "reb": 7.5,
      "ast": 1.4,
      "c": "#5A2D81"
    },
    {
      "rank": 49,
      "player": "Josh Giddey",
      "team": "CHI",
      "war": 3.2,
      "poe": -1.1,
      "def": -0.3,
      "mpg": 32.1,
      "pts": 17.0,
      "reb": 8.3,
      "ast": 9.1,
      "c": "#CE1141"
    },
    {
      "rank": 50,
      "player": "Trey Murphy III",
      "team": "NOP",
      "war": 3.2,
      "poe": 4.3,
      "def": -0.2,
      "mpg": 35.5,
      "pts": 21.5,
      "reb": 5.7,
      "ast": 3.8,
      "c": "#85714D"
    },
    {
      "rank": 51,
      "player": "Amen Thompson",
      "team": "HOU",
      "war": 3.2,
      "poe": -4.0,
      "def": 0.5,
      "mpg": 37.4,
      "pts": 18.3,
      "reb": 7.8,
      "ast": 5.3,
      "c": "#CE1141"
    },
    {
      "rank": 52,
      "player": "Deandre Ayton",
      "team": "LAL",
      "war": 3.1,
      "poe": 18.6,
      "def": -0.4,
      "mpg": 27.2,
      "pts": 12.5,
      "reb": 8.0,
      "ast": 0.8,
      "c": "#552583"
    },
    {
      "rank": 53,
      "player": "Ivica Zubac",
      "team": "LAC",
      "war": 3.0,
      "poe": 3.1,
      "def": -0.0,
      "mpg": 30.1,
      "pts": 14.1,
      "reb": 10.6,
      "ast": 2.2,
      "c": "#C8102E"
    },
    {
      "rank": 54,
      "player": "Miles Bridges",
      "team": "CHA",
      "war": 3.0,
      "poe": -1.5,
      "def": -0.8,
      "mpg": 31.0,
      "pts": 17.1,
      "reb": 5.8,
      "ast": 3.2,
      "c": "#00788C"
    },
    {
      "rank": 55,
      "player": "Mark Williams",
      "team": "PHX",
      "war": 2.9,
      "poe": 3.6,
      "def": -0.3,
      "mpg": 23.6,
      "pts": 11.7,
      "reb": 8.0,
      "ast": 1.0,
      "c": "#E56020"
    },
    {
      "rank": 56,
      "player": "Matas Buzelis",
      "team": "CHI",
      "war": 2.8,
      "poe": -3.9,
      "def": -0.0,
      "mpg": 29.2,
      "pts": 16.3,
      "reb": 5.8,
      "ast": 2.1,
      "c": "#CE1141"
    },
    {
      "rank": 57,
      "player": "Josh Hart",
      "team": "NYK",
      "war": 2.8,
      "poe": 4.9,
      "def": -1.6,
      "mpg": 30.2,
      "pts": 12.0,
      "reb": 7.4,
      "ast": 4.8,
      "c": "#F58426"
    },
    {
      "rank": 58,
      "player": "Lauri Markkanen",
      "team": "UTA",
      "war": 2.8,
      "poe": 3.6,
      "def": -0.4,
      "mpg": 34.3,
      "pts": 26.7,
      "reb": 6.9,
      "ast": 2.1,
      "c": "#00471B"
    },
    {
      "rank": 59,
      "player": "Jaren Jackson Jr.",
      "team": "MEM",
      "war": 2.8,
      "poe": 7.5,
      "def": 0.2,
      "mpg": 30.3,
      "pts": 19.4,
      "reb": 5.7,
      "ast": 2.0,
      "c": "#5D76A9"
    },
    {
      "rank": 60,
      "player": "Jonas Valan\u010di\u016bnas",
      "team": "DEN",
      "war": 2.7,
      "poe": 16.8,
      "def": -3.0,
      "mpg": 13.4,
      "pts": 8.7,
      "reb": 5.1,
      "ast": 1.2,
      "c": "#0E2240"
    }
  ]
};
