(()=>{'use strict';
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg',f=(n,d=2)=>Number.isFinite(n)?n.toFixed(d):'—',sg=n=>(n>0?'+':'')+f(n),norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
let data,season;
function node(tag,text){const n=document.createElement(tag);if(text!=null)n.textContent=text;return n;}
function svg(tag,attrs={},text){const n=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);if(text!=null)n.textContent=text;return n;}
function text(s,x,y,t,attrs={}){s.append(svg('text',{x,y,'font-family':'Arial, sans-serif','font-size':13,fill:'#52685f',...attrs},t));}
function line(s,x1,y1,x2,y2,attrs={}){s.append(svg('line',{x1,y1,x2,y2,stroke:'#dbe2d3',...attrs}));}
function root(w,h,title){const s=svg('svg',{viewBox:`0 0 ${w} ${h}`,role:'img','aria-label':`${title} · ${season.season}`});s.append(svg('title',{},`${title} · ${season.season}`),svg('rect',{width:w,height:h,fill:'#fffdf8'}));text(s,30,31,title,{'font-size':21,fill:'#203e33','font-weight':'bold'});text(s,30,54,`${season.season} regular season · NBAI historical research`,{'font-size':12});return s;}
function rows(body,records){$(body).replaceChildren();for(const record of records){const tr=node('tr');for(const value of record){const cell=node('td');if(value instanceof Node)cell.append(value);else cell.textContent=value;tr.append(cell);}$(body).append(tr);}if(!records.length){const tr=node('tr'),cell=node('td','No players match this search.');cell.colSpan=5;tr.append(cell);$(body).append(tr);}}
function matching(id){const query=norm($(id).value);return season.players.filter(p=>norm(p.name+' '+p.team).includes(query));}
function scoring(){if(!season)return;const list=matching('surplusSearch').sort((a,b)=>($('surplusOrder').value==='low'?1:-1)*(a.scoringSurplus36-b.scoringSurplus36)||a.name.localeCompare(b.name)),top=list.slice(0,15);
 $('surplusCount').textContent=`${list.length} players · Chart shows the first ${top.length} in the ranking · Minimum ${data.minMinutes} minutes.`;
 const s=root(650,Math.max(220,top.length*31+135),'Scoring surplus per 36 minutes'),lo=Math.min(-.5,...top.map(p=>p.scoringSurplus36)),hi=Math.max(.5,...top.map(p=>p.scoringSurplus36)),pad=(hi-lo)*.12,X=n=>255+(n-(lo-pad))/(hi-lo+2*pad)*315;
 for(let i=0;i<=4;i++){const n=lo+(hi-lo)*i/4;line(s,X(n),78,X(n),top.length*31+85);text(s,X(n),top.length*31+106,f(n,1),{'text-anchor':'middle','font-size':11});}line(s,X(0),78,X(0),top.length*31+85,{stroke:'#73866d'});
 for(const [i,p]of top.entries()){const y=82+i*31,v=p.scoringSurplus36,bar=svg('rect',{x:Math.min(X(0),X(v)),y,width:Math.max(1,Math.abs(X(v)-X(0))),height:19,rx:3,fill:v>=0?'#365d4c':'#b45229','data-scorer':p.id});bar.append(svg('title',{},`${p.name}: ${sg(v)} points / 36`));s.append(bar);text(s,242,y+14,p.name,{'text-anchor':'end','font-size':12});text(s,625,y+14,sg(v),{'text-anchor':'end','font-size':12,fill:'#203e33'});}
 if(!top.length)text(s,30,110,'No matching scorers.');$('surplusChart').replaceChildren(s);
 const scorers=new Map(top.map(p=>[String(p.id),p]));NBAI_CHART_TOOLTIPS.attach('surplusChart','[data-scorer]',mark=>{const p=scorers.get(mark.dataset.scorer);return {title:p.name,lines:[p.team+(p.teams>1?' · full season, multiple teams':''),`${sg(p.scoringSurplus36)} scoring surplus / 36`,`${f(p.ts,1)}% true shooting · ${Math.round(p.minutes).toLocaleString()} minutes`,season.season]};});rows('surplusRows',list.map(p=>[p.name,p.team+(p.teams>1?'*':''),sg(p.scoringSurplus36),f(p.ts,1)+'%',Math.round(p.minutes)]));}
function scatter(id,title,records,x,y,xLabel,yLabel,onPick,labels=false){const s=root(900,550,title),xs=records.map(x),ys=records.map(y),minX=Math.min(0,...xs),maxX=Math.max(1,...xs)*1.07,minY=Math.min(0,...ys),maxY=Math.max(1,...ys),rangeY=Math.max(1,maxY-minY),lowY=minY-rangeY*.1,highY=maxY+rangeY*.16;
 // Team baselines cluster around 100; preserve detail without implying a zero origin.
 const lowX=id==='shotValueChart'?Math.min(...xs)-1:minX,highX=id==='shotValueChart'?Math.max(...xs)+1:maxX;
 const X=v=>85+(v-lowX)/(highX-lowX)*730,Y=v=>440-(v-lowY)/(highY-lowY)*340;
 for(let i=0;i<=5;i++){const a=lowX+(highX-lowX)*i/5,b=lowY+(highY-lowY)*i/5;line(s,X(a),100,X(a),440);line(s,85,Y(b),815,Y(b));text(s,X(a),464,f(a,1),{'text-anchor':'middle'});text(s,74,Y(b)+4,f(b,1),{'text-anchor':'end'});}
 if(lowY<0&&highY>0)line(s,85,Y(0),815,Y(0),{stroke:'#73866d','stroke-dasharray':'5 4'});
 text(s,450,500,xLabel,{'text-anchor':'middle',fill:'#203e33'});text(s,25,270,yLabel,{transform:'rotate(-90 25 270)','text-anchor':'middle',fill:'#203e33'});
 const occupied=[];for(const p of records){const c=svg('circle',{cx:X(x(p)),cy:Y(y(p)),r:labels?6:5,fill:'#365d4c',opacity:labels?.85:(p.active?.65:.1),'data-study-point':p.id??p.team});c.append(svg('title',{},`${p.name||p.team} · ${xLabel}: ${f(x(p))} · ${yLabel}: ${f(y(p))}`));c.onclick=()=>onPick(p);s.append(c);
 if(labels){const px=Math.min(790,X(x(p))+8);let py=Y(y(p))-8;for(let tries=0;tries<8&&occupied.some(o=>Math.abs(o.x-px)<31&&Math.abs(o.y-py)<14);tries++)py-=15;if(py>=75){occupied.push({x:px,y:py});line(s,X(x(p)),Y(y(p)),px,py+2,{stroke:'#9bad95','stroke-width':.65});text(s,px,py,p.team,{'font-size':11,fill:'#203e33','paint-order':'stroke',stroke:'#fffdf8','stroke-width':2});}}}
 text(s,30,528,labels?'30 teams · Field goals only · Five-zone descriptive decomposition':`${records.length} players · Minimum ${data.minMinutes} minutes · Hover, tap or focus a dot for player details`,{'font-size':12});$(id).replaceChildren(s);}
function creationHover(){
 const players=new Map(season.players.map(p=>[String(p.id),p]));
 NBAI_CHART_TOOLTIPS.attach('creationChart','[data-study-point]',mark=>{const p=players.get(mark.dataset.studyPoint);return p&&{title:p.name,lines:[p.team+(p.teams>1?' · full season, multiple teams':''),`${f(p.assists36)} assists / 36 · ${f(p.turnovers36)} turnovers / 36`,`${Math.round(p.minutes).toLocaleString()} minutes · ${season.season}`]};},{tooltipId:'creationTooltip',readoutId:'creationReadout'});
}
function creation(){if(!season)return;const list=matching('creationSearch').sort((a,b)=>b.assists36-a.assists36||a.name.localeCompare(b.name)),ids=new Set(list.map(p=>p.id));$('creationCount').textContent=`${list.length} matching players · The league remains visible for context.`;const describe=p=>{$('creationReadout').textContent=`${p.name} · ${p.team}${p.teams>1?' · full-season, multiple teams':''} · ${f(p.assists36)} AST / 36 · ${f(p.turnovers36)} TOV / 36 · ${Math.round(p.minutes)} minutes`;};scatter('creationChart','Assists versus turnovers',season.players.map(p=>({...p,active:ids.has(p.id)})),p=>p.turnovers36,p=>p.assists36,'Turnovers per 36 minutes','Assists per 36 minutes',describe);creationHover();if(list.length)describe(list[0]);else $('creationReadout').textContent='No matching players. Clear the search to restore the full list.';rows('creationRows',list.map(p=>[p.name,p.team+(p.teams>1?'*':''),f(p.assists36),f(p.turnovers36),Math.round(p.minutes)]));}
function teamValue(){if(!season)return;const records=Object.entries(season.teams).map(([team,t])=>({team,...t.shotValue,attempts:t.attempts})),key=$('shotValueOrder').value;const describe=p=>{$('shotValueReadout').textContent=`${p.team} · Baseline ${f(p.baseline)} · surplus ${sg(p.surplus)} · actual ${f(p.actual)} field-goal points / 100 FGA.`;};scatter('shotValueChart','Shot mix versus shot-making',records,p=>p.baseline,p=>p.surplus,'Shot-mix baseline · points per 100 FGA','Shot-making surplus · points per 100 FGA',describe,true);const teams=new Map(records.map(p=>[p.team,p]));NBAI_CHART_TOOLTIPS.attach('shotValueChart','[data-study-point]',mark=>{const p=teams.get(mark.dataset.studyPoint);return {title:p.team+' · '+season.season,lines:[`Shot-mix baseline: ${f(p.baseline)} points / 100 FGA`,`Shot-making surplus: ${sg(p.surplus)} points / 100 FGA`,`Actual: ${f(p.actual)} points / 100 FGA`,`${p.attempts.toLocaleString()} attempts`]};},{readoutId:'shotValueReadout'});const sorted=records.sort((a,b)=>b[key]-a[key]||a.team.localeCompare(b.team));describe(sorted[0]);rows('shotValueRows',sorted.map(p=>{const button=node('button',p.team);button.type='button';button.onclick=()=>{describe(p);$('shotTeam').value=p.team;$('shotTeam').dispatchEvent(new Event('change'));$('shotStudy').scrollIntoView({behavior:'smooth'});};return [button,f(p.baseline),sg(p.surplus),f(p.actual),p.attempts.toLocaleString()];}));}
$('surplusSearch').oninput=scoring;$('surplusOrder').onchange=scoring;$('creationSearch').oninput=creation;$('shotValueOrder').onchange=teamValue;
window.NBAI_STUDIES={render(d,s){data=d;season=s;$('surplusMethod').textContent=data.metricDefinitions.scoringSurplus36;$('creationMethod').textContent=data.metricDefinitions.playmaking;$('shotValueMethod').textContent=data.metricDefinitions.shotValue;scoring();creation();teamValue();}};
})();
